### ISSUE TITLE
大佬，想请教个问题

### ISSUE THREAD

**Issue by code-username** [kuizuo/nest-vben-admin#10]
在使用@nestjs/serve-static进行托管前端打包后的项目文件，

![image](https://github.com/kuizuo/nest-vben-admin/assets/64359368/0dbe7776-2534-49bc-8be8-71aeca1c9977)
运行项目时发生了如下错误
![image](https://github.com/kuizuo/nest-vben-admin/assets/64359368/a7966062-0c46-470c-8d11-18e1c20f644a)

**Comment by kuizuo** [comment]
我没使用过 [`@nestjs/serve-static`](https://docs.nestjs.com/recipes/serve-static) 这个库，不过从文档中有说到，它有将你的api 路径替换的行为，可能就是这个原因导致和你已定义的接口（这里也就是 GET / ）冲突。

**Comment by code-username** [comment]
> 我没有使用过[`@nestjs/serve-static`](https://docs.nestjs.com/recipes/serve-static)这个库，不过从文档中有讲，它有将你的 api 路径替换的行为，可能就是这个原因导致和你已定义的接口（这里只是 GET / ）冲突。

但是项目中确实没有定义过根路径的路由，或者类似‘/*’这种，所以也不知道在哪里改，在使用fastify那个静态资源服务时也是报了类似的问题

**Comment by code-username** [comment]
如果不行的话估计前端就得单独进行部署了，我是想这样会方便一些

**Comment by kuizuo** [comment]
会不会是你所指向的目录(public)，正好是 app.useStaticAssets 所定义的静态资源目录所导致的？

https://github.com/kuizuo/nest-vben-admin/blob/6dc21e5ea484bc76e2775df25904a40c4c430fda/apps/api/src/main.ts#L59

**Comment by code-username** [comment]
> 不会是你所指向的目录（public），正好是app.useStaticAssets所定义的静态资源目录所导致的？
> 
> https://github.com/kuizuo/nest-vben-admin/blob/6dc21e5ea484bc76e2775df25904a40c4c430fda/apps/api/src/main.ts#L59

是的，谢谢大佬，确实是这个问题
