### ISSUE TITLE
 TypeError: JwtStrategy requires a secret or key

### ISSUE THREAD

**Issue by oynasun** [kuizuo/nest-vben-admin#13]
![image](https://github.com/kuizuo/nest-vben-admin/assets/101538550/59bcb6c8-e07f-42ce-bba2-dd6fcff86d5b)
![微信图片_20231230005040](https://github.com/kuizuo/nest-vben-admin/assets/101538550/19770ef7-6855-45f5-be16-b3aa264869cf)

**Comment by kuizuo** [comment]
Rename `.env.development.bak` to `.env.development`
