### ISSUE TITLE
求助：数据库问题

### ISSUE THREAD

**Issue by JeromeD3** [kuizuo/nest-vben-admin#14]
![微信截图_20240130165738](https://github.com/kuizuo/nest-vben-admin/assets/67688096/0543b8ab-6d55-4b26-89be-3b91336ebb58)

**Comment by kuizuo** [comment]
能否提供你的环境变量 .env 的内容？ 

我猜测你数据库可能添加了 ssl 验证，因此你可能需要到 database.config.ts 中添加 ssl: false 来解决。

**Comment by kuizuo** [comment]
这个问题我没遇到过，不过看样子应该是 Mysql 的服务所导致的，你可以添加 ssl: false 或 insecureAuth: true 这两个属性来尝试解决。

**Comment by JeromeD3** [comment]
话说为什么不用mysql2去连接数据库，而选择了mysql这个包呢呢？

**Comment by kuizuo** [comment]
> 话说为什么不用mysql2去连接数据库，而选择了mysql这个包呢呢？

这是个好建议，至于为何选择mysql，是因为本项目我是从旧版本不断演进的，我主要更新了几个核心的包，而由于数据库依赖几乎怎么改动，在意一个 mysql 版本。

不过官方也推荐安装 mysql2，该项目后续会对此有所改进。
