### ISSUE TITLE
项目运行问题

### ISSUE THREAD

**Issue by qixm-burnish** [kuizuo/nest-vben-admin#7]
在`clone main`分支后，mysql数据库导入`admin/sql`文件，使用`pnpm install`安装完依赖后，运行项目`pnpm run dev`，还是有几个问题麻烦确认下：
1. 默认的前端项目是展示的全部路由，好像需要把权限模式配置成后端吧。如果是的话，可以在文档中说明一下或直接修改成这种
![ivF4WH.png](https://i.328888.xyz/2023/04/26/ivF4WH.png)

3. 在`步骤1`之后，重新登录时获取用户菜单列表会报错，经排查发现下面的查询结果为空(对typeORM不熟悉)
![ivFb9V.png](https://i.328888.xyz/2023/04/26/ivFb9V.png)

5. 按`上图`修改之后，可以成功获取到路由列表，但是点击菜单栏切换到系统管理下面的子菜单会出现404，调试permission.ts中`router.addRoutes`是正常的，`router.getRoutes()`也可以成功获取动态路由。版本为`vue-router: 4.1.6`，暂不清楚是哪边的问题。
![ivF5kF.png](https://i.328888.xyz/2023/04/26/ivF5kF.png)

7. 另外建议把admin项目的souremap开启，便于调试接口。
![11](https://i.328888.xyz/2023/04/26/ivFo9Q.png)

**Comment by kuizuo** [comment]
不好意思，目前项目处于重构阶段，主要针对整合vben最新代码以及后端目录结构，即monorepo。

针对你的这些问题，我还未将一些组件迁移过去，因此访问这些路由地址会得到404，近期我会不断迁移过去进而解决这个问题

**Comment by qixm-burnish** [comment]
重构这种建议通过新分支解决，完成后通过pr合并至主分支，以保证主分支可以正常运行
