### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by songlin51** [kuizuo/nest-vben-admin#9]
您好,想请教一个问题. 这种前后端分离项目的权限是不是api没有做限制.
比如我有编辑角色权限, 但是我直接用token请求后端无权限的api ( 创建用户接口) , 是不是也可以调用通.

正常是不是需要再给菜单关联上对应的后端api地址?

**Comment by kuizuo** [comment]
针对每个接口肯定是有做权限的，不过这里的权限主要是以菜单的形式展示。比如说

比如说我先定义了菜单(权限)
![image](https://github.com/kuizuo/nest-vben-admin/assets/61005888/7f3910eb-c8cf-4746-99d9-5846edf84059)

然后我给某个角色分配了这几个权限，在这里也就是新增，更新，删除，等。
![image](https://github.com/kuizuo/nest-vben-admin/assets/61005888/0568f6a9-6522-4540-91b7-391ec7bdc6c7)

就以你的假设为例，如果分配该这个角色没有创建用户的权限，那么请求创建用户接口就会提示无权限，至于说是怎么表示这个权限的，一般都有一个权限码，比如说 我这里为 `system:role: create`。

**Comment by kuizuo** [comment]
> 正常是不是需要再给菜单关联上对应的后端api地址?

针对这个需要补充，我之前的做法是按路径的形式，比如说 权限码 为 `system:role:create`, 在中间件的时候就会将其转换为 `system/role/create` 也就是 后端 api 地址，但这样的话会缺失灵活性，比如想用 restful 风格的接口格式就不行了。

而后面我则是在对应的接口控制器中添加一个注释，比如说 

```
@Permission('system:role:create')
create(){
  // ...
}
```

**Comment by songlin51** [comment]
了解了,感谢作者回复.
